/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ceiba.parking;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.web.context.WebApplicationContext;

import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class ParkingTest {

	private MockMvc mockMVC;
	@Autowired
	private WebApplicationContext context;
	
}
